### ISSUE TITLE
the current install requires a LOT of workarounds for shared folders to work properly.

### ISSUE THREAD

**Issue by canariecaf** [lawlesst/vivo-vagrant#29]
**The Problem**
When trying to go 'vagrant up', vagrant hangs when using precise64 image because it cannot properly get a share made to the host.
This is on mac using Vagrant 1.8.1 with the following plugins:
vagrant-hostmanager (1.8.1)
vagrant-share (1.1.5, system)
vagrant-vbguest (0.12.0)

The work around is to use a variation of this recommendation:
http://stackoverflow.com/questions/22717428/vagrant-error-failed-to-mount-folders-in-linux-guest

`
git clone 
vagrant up —no-provision
# Expect this to get an error, now let's fix it since it did provision a machine

vagrant ssh
sudo bash
# Per: http://stackoverflow.com/questions/22717428/vagrant-error-failed-to-mount-folders-in-linux-guest

ln -s /opt/VBoxGuestAdditions-4.3.10/lib/VBoxGuestAdditions /usr/lib/VBoxGuestAdditions
# exit from the sudo shell

exit
# exit from the vm

exit
# reload the vm

vagrant reload —no-provision
# vagrant ssh into the machine and verify the shares there

vagrant suspend
# the below command will bring the machine up and init provisioning actions

vagrant resume 
`

I would like to suggest that to resolve this issue is to explore the original VM used and verify that network shares work on both Mac and WIndows adjusting documentation accordingly.

**Comment by lawlesst** [comment]
This should be unnecessary. It hasn't been an issue in the past and I wasn't able to replicate on a Mac with Vagrant 1.8.3 and Virtualbox 5.0. 

I would recommend upgrading Virtualbox to 5.0 but not a more recent version since there's a reported [issue](https://github.com/mitchellh/vagrant/issues/7581) with Virtualbox 5.x on Macs.

Copying @senrabc because he uses this extensively on Macs. Chris, have you encountered this problem?
